name: Build Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

concurrency:
  group: ${{ github.workflow }}-${{ inputs.php-version }}
  cancel-in-progress: true

jobs:
  trigger-build:
    if: ${{ github.repository == 'nayleen/docker-php' }}
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
    steps:
      - name: Build PHP${{ matrix.php }} Images
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yaml
          inputs: '{ "php-version": "${{ matrix.php }}" }'
