name: Build Images

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  schedule:
    # run every Monday and Friday at 00:00 UTC
    - cron: '0 0 * * 1,5'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOCAL_REGISTRY: localhost:5000
      REMOTE_REGISTRY: docker.io/nayleen
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Export PHP Version to ENV
        run: echo "PHP_VERSION=${{ matrix.php }}" >> $GITHUB_ENV

      - name: Export Image Name to ENV
        run: echo "IMAGE=${{ env.REMOTE_REGISTRY }}/php:${{ matrix.php }}" >> $GITHUB_ENV

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build Local Images
        uses: docker/bake-action@v6
        env:
          REGISTRY: ${{ env.LOCAL_REGISTRY }}
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          source: .
          load: true
          push: true
          set: |
            php.cache-from=type=registry,ref=${{ env.IMAGE }}-cache

      - name: Test Local Images
        env:
          REGISTRY: ${{ env.LOCAL_REGISTRY }}
        run: |
          # assume each subfolder of ./tests is a test suite and run it
          for test in $(find ./tests/* -type d); do
            cd $test && ./run.sh
            cd - > /dev/null
          done

      - name: Set up QEMU
        if: github.event_name != 'pull_request'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Bake and Push Docker Images
        if: github.event_name != 'pull_request'
        uses: docker/bake-action@v6
        env:
          REGISTRY: ${{ env.REMOTE_REGISTRY }}
        with:
          source: .
          push: true
          set: |
            php.platform=linux/amd64,linux/arm64
            php.cache-from=type=registry,ref=${{ env.IMAGE }}-cache
            php.cache-to=type=registry,ref=${{ env.IMAGE }}-cache,mode=max
