name: Build Images

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ inputs.php-version }}
  cancel-in-progress: true

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.3
          - 8.4
    steps:
      - name: Build PHP${{ matrix.php }} Images
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yaml
          inputs: '{ "php-version": "${{ matrix.php }}" }'
