name: Build Images

on:
  workflow_dispatch:
    inputs:
      php-version:
        required: true
        type: string
        description: 'PHP version to build'

concurrency:
  group: ${{ github.workflow }}-${{ inputs.php-version }}
  cancel-in-progress: false

jobs:
  build:
    if: ${{ github.repository == 'nayleen/docker-php' }}
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-22.04' || 'ubuntu-22.04-arm' }} # nice performance regression, 24.04 on arm
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - php: ${{ inputs.php-version }}
    steps:
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/nayleen/php
          tags: |
            type=raw,value=${{ matrix.php }}-${{ matrix.arch }}

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nayleen
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
          cache-from: type=registry,ref=ghcr.io/nayleen/php:${{ matrix.php }}-${{ matrix.arch }}-cache
          cache-to: type=registry,ref=ghcr.io/nayleen/php:${{ matrix.php }}-${{ matrix.arch }}-cache,mode=max
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  combine-manifests:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nayleen
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Combine Manifests
        run: |
          docker buildx imagetools create -t ghcr.io/nayleen/php:${{ inputs.php-version }} \
            ghcr.io/nayleen/php:${{ inputs.php-version }}-amd64 \
            ghcr.io/nayleen/php:${{ inputs.php-version }}-arm64
