name: Check Upstream Image

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

jobs:
  check:
    if: ${{ github.repository == 'nayleen/docker-php' }}
    runs-on: ubuntu-22.04
    permissions:
      actions: write
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
    outputs:
      changed: ${{ steps.compare.outputs.changed }}
    steps:
      - name: Fetch Upstream Image Digest
        run: |
          echo "$(docker buildx imagetools inspect "php:${{ matrix.php }}-cli" --format "{{json .Manifest}}" | jq -r .digest)" > ./current-digest-${{ matrix.php }}

      - name: Download Previous Digest
        uses: actions/cache/restore@v4
        with:
          key: previous-digest-${{ matrix.php }}
          path: ./previous-digest-${{ matrix.php }}
        continue-on-error: true

      - name: Compare Digests
        id: compare
        run: |
          touch ./previous-digest-${{ matrix.php }}

          echo "Comparing current and previous digests for PHP${{ matrix.php }} upstream image:"
          echo "  current: $(cat ./current-digest-${{ matrix.php }})"
          echo "  previous: $(cat ./previous-digest-${{ matrix.php }})"

          if ! cmp -s ./current-digest-${{ matrix.php }} ./previous-digest-${{ matrix.php }}; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build PHP${{ matrix.php }} Images
        if: ${{ steps.compare.outputs.changed == 'true' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yaml
          inputs: '{ "php-version": "${{ matrix.php }}" }'
